language: rust
sudo: required
dist: bionic
addons:
    apt:
        packages:
            - build-essential
            - libssl-dev
            - libgtk-3-dev
            - libsdl2-dev
            - libsdl2-ttf-dev
rust:
    - stable
    - nightly
matrix:
  - os: linux
    rust: nightly
    env: GTK=3.14
  - os: linux
    rust: stable
    env: GTK=3.14

  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

script:
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi