language: rust
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libgtk-3-dev

before_install: |
  set -x
  # Install ubuntu dependencies
  #sudo apt install libwebp-dev libtiff-dev
  #sudo apt install libvorbis-dev libflac-dev libfluidsynth-dev libmodplug-dev

  # Download source archives
  # wget https://www.libsdl.org/release/SDL2-2.0.9.tar.gz https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz
  wget https://www.libsdl.org/release/SDL2-2.0.9.tar.gz

  # Unpack archives
  # ls SDL2*.tar.gz | xargs -i tar -zxvf {}
  wget https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
  tar -zxvf SDL2-2.0.9.tar.gz
  cd SDL2-2.0.9
  ./configure
  make
  sudo make install

  cd ..
  ls -alh

  wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz
  tar -zxvf SDL2_ttf-2.0.15.tar.gz
  cd SDL2_ttf-2.0.15
  ./configure
  make
  sudo make install

  ls -alh /usr/local/lib
  rustc --print sysroot
  echo $LD_LIBRARY_PATH

  # Compile packages
  # ls -d SDL2*/ | xargs -i bash -c "cd {} && ./configure && make"
  # Install packages
  # ls -d SDL2*/ | xargs -i bash -c "cd {} && sudo make install"

# before_cache: |
#   if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
#     RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
#   fi
#   # Install ubuntu dependencies
#   sudo apt install libwebp-dev libtiff-dev
#   sudo apt install libvorbis-dev libflac-dev libfluidsynth-dev libmodplug-dev

#   # Download source archives
#   wget https://www.libsdl.org/release/SDL2-2.0.9.tar.gz https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz

#   # Unpack archives
#   ls SDL2*.tar.gz | xargs -i tar -zxvf {}

#   # Compile packages
#   ls -d SDL2*/ | xargs -i bash -c "cd {} && ./configure && make"
#   # Install packages
#   ls -d SDL2*/ | xargs -i bash -c "cd {} && sudo make install"
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo clean --verbose
  - cargo build --verbose
  - LD_LIBRARY_PATH=/usr/local/lib cargo test --verbose

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    # cargo tarpaulin --out Xml
    # bash <(curl -s https://codecov.io/bash)
  fi
