language: rust
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libgtk-3-dev

env:
  - LD_LIBRARY_PATH=/usr/local/lib
cache: cargo

before_install: |
  wget https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
  tar -zxvf SDL2-2.0.9.tar.gz
  cd SDL2-2.0.9
  ./configure && make && sudo make install
  cd ..

  wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz
  tar -zxvf SDL2_ttf-2.0.15.tar.gz
  cd SDL2_ttf-2.0.15
  ./configure && make && sudo make install
  cd ..

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo clean
  - cargo build
  - cargo test --lib

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
